default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dallasrb
  password: dallasrb

development:
  <<: *default
  database: dallasrb-web_development

test:
  <<: *default
  database: dallasrb-web_test

production:
  <<: *default
  database: dallasrb-web_production
